version: '3'

services:
  web:
    image: richardreveron1/debian:1.08
    container_name: debian
    volumes:
#    Change the left part here if you are using a framework like laravel to start there, or.. change the apache virtual host
      - ${WWW_PATH}:/var/www/html/:delegated
      - ./apache:/etc/apache2/sites-enabled:delegated
    ports:
      - 80:80
    networks:
      - overlay
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - overlay

  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - overlay

    ports:
      - 3306:3306
networks:
  overlay: