version: '3'

services:
  web:
    image: richardreveron1/debian:1.07
    container_name: debian-and-compose
    volumes:
#    Change the left part here if you are using a framework like laravel to start there, or.. change the apache virtual host
      - ./html:/var/www/html/:delegated
    ports:
      - 80:80

  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

    ports:
      - 3306:3306